version: "3"
services:
  nats:
    image: bitnami/nats:latest
    expose:
      - "4222"
    ports:
      - "8222:8222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222"]
      interval: 30s
      timeout: 10s
      retries: 5

  service:
    build: .
    entrypoint: make run/service
    environment:
      - NATS_URL=nats://nats:4222
    restart: on-failure
    depends_on:
      - nats
    links: 
      - nats
  
  client:
    build: .
    entrypoint: make run/client
    environment:
      - NATS_URL=nats://nats:4222
    restart: on-failure
    depends_on:
      - nats
    links: 
      - nats